### ISSUE TITLE
投稿后显示上传失败

### ISSUE THREAD

**Issue by nuomi** [cnbeining/bilidirectuploader#1]
上传后获得了上传代码：

151519232/152462549 done...
152043520/152462549 done...
152567808/152462549 done...

Hope everything is fine.
[vupload]95d3705e023aa6b129141de128a8b183;Advanced Debugging Techniques with Chrome - @Scale 2014 - Web-B63jNjSVEbQ.mp4;2;[/vupload]

但是，通过代码模式，填写上传代码，补充填写视频相关的标题，标签，分区，简介等信息之后，点击“确定投稿”。

之后在投稿管理中，发现“上传失败”
## 

另外，也尝试了在上传代码后面补充分p信息，变成

[vupload]95d3705e023aa6b129141de128a8b183;Advanced Debugging Techniques with Chrome - @Scale 2014 - Web-B63jNjSVEbQ.mp4;2;[/vupload]#p#P1#e#

依然上传失败

**Comment by cnbeining** [comment]
恭喜您，我也觉得这个脚本死了。

至于怎么修呢？我也不知道。

麻烦大家集思广益吧 我是怎么着都没模拟出来 不知道为啥。。。

**Comment by nuomi** [comment]
经过仔细对比，我发现：
目前bili网站上，上传文件的POST请求中 ：   Content-Length:1049774
而代码中  Content-Length': '524288'

然而改成1049774之后上传，提交，仍然显示上传失败。。。

**Comment by nuomi** [comment]
按照官方提示，代码模式的例子是这样的：
[vupload]xxxxxxxx[/vupload]#p#分P1名称#e#    

然而从网页上传，然后点开代码模式，发现代码是这样事儿的：
[vupload]xxxxxxxx[/vupload]

那么，到底怎么着才是正确格式啊？

**Comment by nuomi** [comment]
我擦，我发现我的账号已经不能正常登陆了。。。。
我怎么了我！！！

**Comment by cnbeining** [comment]
节哀顺变。

虽然我觉得这是偶发现象：他设置cookie的方法是好几次301.

**Comment by nuomi** [comment]
确实偶发，又活过来了
